### ISSUE TITLE
Movies starting with special characters get removed from the database

### ISSUE THREAD

**Issue by Bloodsoul** [jreklund/php4dvd#13]
I got some issue with movies, that start with special characters such as dots, quotation marks or brackets.

It seems that updating all movies or the update process to 3.6.1 has removed all movies starting with one of them from the database. I try to figure out if I can reproduce it, when I manage to re-add them. They are still in the cache directory.

**Comment by Bloodsoul** [comment]
And they are back again. I have no idea, where they did get, and how they came back. Could this come from an already running update process?

**Comment by jreklund** [comment]
There were no changes done to the database structure in 3.6.1. Only what value to store for Parental Guidance and how to grab it from $_COOKIE/$_GET.

**Comment by Bloodsoul** [comment]
Then I'm just stupid. Nevermind. :)

**Comment by jreklund** [comment]
No problem. :-) It always asks for database upgrade, even thought there ain't none.
