### ISSUE TITLE
Change language on movie titles

### ISSUE THREAD

**Issue by alireza12186** [jreklund/php4dvd#15]
I really like php4dvd. but I have a problem with it. my server that I installed php4dvd on it is located in Germany. so when I search for a movie or update a movie it replaces English title with German title. but I don't know German and I'd like to have titles in English. 

How can I fix it ?

**Comment by jreklund** [comment]
Hi @alireza12186, at the moment I don't have a configuration option for this. I'm waiting on the latest update of imdbphp; that I made a pull request for. After that php4dvd will have a "complete" fix for changing language, for then your server aren't "talking" English. 
At the moment you can change this .ini file directly:
php4dvd/lib/imdbphp/conf/php4dvd.ini

Remove the semicolon and change it into this:
```language = 'en-US,en'```

It only works for movies/tv-series that have English titles, those who have only Japanese and English title in "Worldwide" will not work with this. But a fix for that are on it's way.

**Comment by alireza12186** [comment]
Thanks @jreklund 
It didn't work for some titles. but generally it was useful. I changed the line and tried to update a movie. I selected "some like it hot" . It's an American movie so it's name is English. but after updating it, again it's name showed in German. after that I entered many titles and all of them was English . thanks

**Comment by jreklund** [comment]
No problem @alireza12186, thanks for the feedback.
If you previously added that movie (1 week) you will need to empty your /cache folder, or wait one week. And update it again. If that's not working, you will need to wait for the next release. I will add a way to select a remote IP-adress (English IP/American IP) so that IMDb think you are connecting from that country.

**Comment by alireza12186** [comment]
thank you very much @jreklund . your solution worked well for me. 

appreciate you

**Comment by jreklund** [comment]
There are now a complete fix available.
You can read more about it in the readme; [Configure languages](https://github.com/jreklund/php4dvd#configure-languages)

**Comment by alireza12186** [comment]
thanks @jreklund 
I prefer to wait for new version. I think It will be good if search results show the original language of movie. I added 275 titles today and non-english titles show in German because my server is located in Germany. 

thanks

**Comment by jreklund** [comment]
You should try the new `$settings["imdbphp"]["ip_address"]` option. You can now "be" in UK/US if you specify a UK/US based ip-address. That will at least give you the English title.

There are also `$settings["imdbphp"]["langauge"]` available, that's same as  `php4dvd.ini` as mentioned earlier.

Can you give me a couple of IMDb ID's I can experiment on, that's non-english, that you have added. Don't have any in my own collection.

You wan't the search results in the original language?
You wan't the movie "Title" (after you select a movie) to be in the original language?
Even if you specify another language inside  `$settings["imdbphp"]["langauge"]`?

**Comment by alireza12186** [comment]
I tried all of settings you mentioned before. (imdbphp, php4dvd.ini, ip). 
these are some examples. please you check them agian. 
The Water Diviner       Das Versprechen eines Lebens
The Piano                        Das Piano
The Patience Stone    Stein der Geduld
Winter Sleep                  Winterschlaf


I just want search and add a title in English. even if my server is in different place. 

thanks

**Comment by jreklund** [comment]
I'm sorry but those works just fine using the following.
```php
$settings["imdbphp"]["langauge"] = 'en-US,en';
$settings["imdbphp"]["ip_address"] = '127.0.0.1'; // Insert a UK/US IP-address
```
I can also return them in Swedish, German, etc just fine.
There aren't anything I can do if this ain't working for you.

Remember to also empty your /cache folder before trying new settings, your search results are kept for 1 week at the time.
