### ISSUE TITLE
"Plots" formatting

### ISSUE THREAD

**Issue by bosguy123** [jreklund/php4dvd#2]
Same as the original project, the plots are formatted with an ordered list with a number, which makes them have a new number every time there is a line break in the information that comes over from IMDB.

![php4dvd issue](https://cloud.githubusercontent.com/assets/24983876/21747279/c2f06a9a-d52f-11e6-9580-f865f12936cd.png)

**Comment by jreklund** [comment]
Hi @bosguy123,
Thanks for you feedback. I have now updated the project with a more "normal" look.

You will need to insert it in the following order:
`Plots summery on one line, you can't use "Enter". Works perfect with IMDb.
- (hyphen)
Author`

![batman-1989](https://cloud.githubusercontent.com/assets/3641536/21749750/ac661830-d5a5-11e6-90e5-da75d3f0a96d.jpeg)
