### ISSUE TITLE
user registration

### ISSUE THREAD

**Issue by duohost** [jreklund/php4dvd#22]
If guest mode is disabled site is restricted and need to login.
Can you make registration for users ?

**Comment by jreklund** [comment]
You want some approval system or everybody get's access to all public data?

**Comment by duohost** [comment]
This would be good feature, after user register, he can save movies to his account and make a list.
Also it would be great that users can get email notification about new movies added, based on genres.

**Comment by jreklund** [comment]
That's features I'm not aiming for. You will need to do a major rewrite.
But a request registration/open registration to be able to see movies aka closed guest view are possible.
