### ISSUE TITLE
Can't log in after fresh install

### ISSUE THREAD

**Issue by zelmon64** [jreklund/php4dvd#24]
Hi,

I've installed v3.7.0 and deleted the`install/` directory. That all went smoothly and I can now view php4dvd but when I try to log in I get error 500. I enabled all the debugging and now get the following:
```
SELECT `users`.* FROM `users` WHERE username = 'admin' LIMIT 1 -- keep-cache
resultset: 1 rows
```
I understand this is something to do with SQL but I have no clue how to fix it. What does this message mean?

I'm using lighttpd instead of Apache. Could that be a problem? I've installed the rest of packages in the **[Requirements](https://github.com/jreklund/php4dvd#requirements)** section. Could I still be missing a package (I'm running OpenWRT CC on a Zsun WiFi card reader so my environment is quite stripped down)?

Thanks :)

**Comment by jreklund** [comment]
Hi,

I just tried a clean install without any errors. So I'm afraid it's your configuration. Error 500 are a webbserver error message and can only be viewed in your php_error.log and lighttpd_error.log.

That SQL query just says it's looking for a user named 'admin', and cache the results. After that it's gets terminated, if that's the only thing you see.

lighttpd works fine with PHP. Haven't tested it together with my requirements thought.

**Comment by zelmon64** [comment]
@jreklund thanks for testing it out. In the lighttpd_error.log it said there was a problem with `hash` so I installed `php5-mod-hash` and it now works!

Thanks again :)
