### ISSUE TITLE
Add scraping support for csfd.cz [Czech]

### ISSUE THREAD

**Issue by jakub96124124** [jreklund/php4dvd#25]
Good day could not add drawings from this database add pumping from https://www.csfd.cz/ Otherwise thanks for reply

**Comment by jreklund** [comment]
Hi, I'm sorry but I don't understand what you mean by "pumping".
This script only supports IMDb.

**Comment by jakub96124124** [comment]
she would not be doing csfd.cz support there

**Comment by jreklund** [comment]
There are currently no official API and no complete unofficial PHP crawler.
https://github.com/search?l=PHP&q=CSFD&type=Repositories&utf8=%E2%9C%93
So it's to much work for supporting one language.

**Comment by jakub96124124** [comment]
https://github.com/jirutka/CSFD-parser

**Comment by jreklund** [comment]
That's a Python parser, this project is based on PHP.

**Comment by jakub96124124** [comment]
https://github.com/Mikulas/csfd-api
https://github.com/MattSkala/csfd-api

**Comment by jreklund** [comment]
Those are 4 and 5 years old. So they are abandoned.

**Comment by jakub96124124** [comment]
I would be delighted to contribute to the development and support of the Czech database

**Comment by jreklund** [comment]
Sure, these are the main files using imdbphp at the moment. These needs to be rewritten to support multiple API.
includes\movie.inc.php
includes\movie.update.inc.php
lib\db\Movie.class.php

**Comment by jakub96124124** [comment]
https://github.com/PatrikValkovic/csfd-api
