### ISSUE TITLE
Url is forced to https despite configuration

### ISSUE THREAD

**Issue by kkayacan** [jreklund/php4dvd#27]
force http setting is false in configuration but site is redirected to https starting from install. What might be the problem?

**Comment by jreklund** [comment]
Have you accidentally activated it inside `.htaccess`?

**Comment by kkayacan** [comment]
This is .htaccess under /php4dvd folder:

`# no indexing
Options -Indexes +FollowSymLinks -MultiViews

# hidden files
<Files ~ "common.inc.php">
	Order Deny,Allow
	Deny from all
</Files>

<IfModule mod_rewrite.c>
  RewriteEngine On
  # Force HTTPS.
  # By deleting "#" on the next two rows. 
  #RewriteCond %{HTTPS} !=on
  #RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
  
  # !IMPORTANT! 
  # Set your RewriteBase here and don't forget trailing and leading slashes.
  # If your page resides at
  #  http://www.example.com/app/php4dvd
  # then use
  # RewriteBase /app/php4dvd/
  RewriteBase /
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^ index.php [QSA,L]
</IfModule>

<IfModule !mod_rewrite.c>
  ErrorDocument 404 /index.php
</IfModule>`

**Comment by jreklund** [comment]
That looks good, regarding https.
If you wan't to use SEO urls you need to change `RewriteBase /` into `RewriteBase /php4dvd/`.

If you delete that file (.htaccess) entirely and remove the following lines:
https://github.com/jreklund/php4dvd/blob/master/common.inc.php#L56

```php
// Force the use of HTTPS
if(
	isset($settings["url"]["HTTPS"]) && $settings["url"]["HTTPS"] && 
	(!isset($_SERVER['HTTPS']) || $_SERVER['HTTPS'] !== 'on')
) {
	header('Location: https://'. $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"], true, 301);
	exit();
}
```

Then you have removed all redirect functions regarding https from php4dvd. If it still redirects you it's your webbserver* that's the problem. 
* Apache, Nginx etc

**Comment by kkayacan** [comment]
OK, redirection seems to be gone right now. Thanks for the tip.

But links (and resource file urls like css) still start with https and site is a little broken. I think that is because installation is done with https base url. Shall I start over the installation with removing those?

**Comment by jreklund** [comment]
Ok, could you add .htaccess file again and then the php code. Too see what actually triggers your redirect.

If you delete this, it ignores the servers HTTPS settings.
https://github.com/jreklund/php4dvd/blob/master/common.inc.php#L74
```php
if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']) {
	$protocol = "https";
}
if(isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO']) {
	$protocol = "https";
}
```

Can you post some information about your server software and custom settings. This should't even happen. The redirect can't even activate if you have `$settings["url"]["HTTPS"] = false;`.

**Comment by kkayacan** [comment]
I restored .htaccess and added PHP code. No redirection..

I am on Byethost shared hosting free plan so I don't have any custom configuration.

Here is server info:
https://docs.google.com/spreadsheets/d/1v6Ssxac-WbJnaq5Aq_fP-s7mJU1MKZOX5vVmvU1nZlU/edit?usp=sharing

**Comment by jreklund** [comment]
That's indeed strange... will create a free account later and see if I can replicate this.
Do you get http:// links now for CSS or is that still a problem?

**Comment by kkayacan** [comment]
Links are still https. I'll try starting over installation with the php code removed.

**Comment by jreklund** [comment]
Okey, keep me posted on what you find.
It was I who deleted your phpinfo links. Those type of information should't be made public. I have saved it.

**Comment by kkayacan** [comment]
![resim](https://user-images.githubusercontent.com/5430694/35937269-c25b1954-0c56-11e8-94f9-e7047c3a9600.png)

Unfortunately, base url is still https.

**Comment by jreklund** [comment]
Ok, I have now created a free account. Apparently Bytehost utilizes a load balance and sets `$_SERVER['HTTP_X_FORWARDED_PROTO']` as `http`. There are currently no checks in the current version for a true `https` string, so it's just assume you want an encrypted connection.

Change row 77-79 in common.inc.php into:
```php
if(isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
	$protocol = "https";
}
```

If it's works out for you too, I will release a new version with this fix.

**Comment by kkayacan** [comment]
Works great. Thank you very much.
