### ISSUE TITLE
option to add stream

### ISSUE THREAD

**Issue by duohost** [jreklund/php4dvd#28]
Is it possible to add option to add stream like here http://muzika.gq/infos.html?option=3 ?
Project from https://github.com/Ho-Ri-ZoN/CMS-Stream

**Comment by jreklund** [comment]
There are many things that needs to be done to be able to make a good streaming platform. Here are a few;
1. Encode video in 5-7 qualities (144p, 240p, 360p, 480p, 720p, 1080p...) or re-encode in real time. Youtube are currently using vp9 and opus in webm.
2. Adaptive streaming or progressiv download.
3. Find a capable html5/Javascript player e.g. [google/shaka-player](https://github.com/google/shaka-player).
4. Add ads playback before video / Ads on the site / Paying member.
 (For supporting the license fees of movies/tv-shows).

There are a few open source video platforms out there and some you need to pay a few bucks for. It would be easier to add IMDb/TMDb support to a already working video streaming project than adding all that functionality into php4dvd.

There are currently a beta branch for local video playback using VLC Player.
