### ISSUE TITLE
Allow searching on media type

### ISSUE THREAD

**Issue by jdeluyck** [jreklund/php4dvd#3]
Hello,

Would it be possible to incorporate searching on media type? I've tried adding this myself, but I seem to be missing some part somewhere. Tried it on my own repo at https://github.com/jdeluyck/php4dvd/ - but modifications are from dec/jan.

**Comment by jreklund** [comment]
Hello,

Change your php4dvd.js line 53 into:
`url += "&f=" + encodeURIComponent(f);`

In sidebar.html I added "All", so you don't have to choose.
```
<select id="format" onchange="search();">
	<option value="0">{$smarty.const.ALL|htmlentities:3:'UTF-8'}</option>
	{section name=f loop=$movieformats}
	<option value="{$movieformats[f]}">{translate($movieformats[f])|htmlentities:3:'UTF-8'}</option>
	{/section}
</select>
```
After merging my repo you got some `<<` inside all language files. So everything just crashed. FORMAT is also defined already. Just open my language files, and paste them into yours.

**Comment by jdeluyck** [comment]
Thanks, that indeed did the trick. I'd been searching for a while but i completely missed that one 's' ;)

Also a big thanks for keeping this project alive!

**Comment by jreklund** [comment]
Yeah, I missed it at first too. I discovered it by looking at the "Network" inside Developer Tools (Chrome) and saw that it got the wrong format; f=name%20asc.

You're very welcome. This is my first time giving back to the community, have "stolen" so much in the past. Just open a new issue if you come up with a new feature or find a bug.

Things planned for future releases:
- [ ] TV-icon on movie posters / TV on text-display
- [ ] Favorite (Movie/TV-series) - Also icon on posters
- [ ] Display (sort/layout); Movie | TV-Series | Own | Seen | Favorites
- [ ] Bug: 1h 0min (on 60min runtime)
