### ISSUE TITLE
User ratings?

### ISSUE THREAD

**Issue by MESWEB** [jreklund/php4dvd#32]
Can You implement user ratings? This function is useful.

**Comment by jreklund** [comment]
Technically `rating` are based on user ratings (`votes`).
But I guess you want a separate one based on your own rating.
And replacing `rating` in "Sort by", "Layout" and on the movie/tv-show itself.

**Comment by MESWEB** [comment]
Yeah that's it. User vote by his rate and own website storing this rating to sorting or recommending other movies  for this user.

**Comment by jreklund** [comment]
There are currently no functionality to recommend other movies/tv-shows based on what you have added or voted on. And at this time I don't know exactly how to do so.
Personally I think favourite are enough, that's why I added a poll/voting on this feature.

**Comment by MESWEB** [comment]
It's simple. User vote 8/10 for Matrix and system recommending this same film genre with high vote points.
Own vote system keep searching more clear for other countries like Europe. USA have different point of view to this same movie displayed in other countries. So imdb get different vote than I was expect. Sometimes I see very very good movie and imdb was 5.6 vote rating where this same movie in polish website was 7.5 vote rating. So personally I recommending add own vote system to this script.

**Comment by jreklund** [comment]
I know the theory behind it. But you also need to code it.
At this time you can always edit the rating.

**Comment by MESWEB** [comment]
Ok let's start. Add colum rating to user table.

**Comment by jreklund** [comment]
Like I said before, I'm awaiting votes from other users on this. I'm not going to code something I don't deem necessary.

**Comment by jreklund** [comment]
No votes have been made or any feedback from other users. I will close this one. Open a new Issue in the feature if it's still desired.
