### ISSUE TITLE
Index Number for private libraries?

### ISSUE THREAD

**Issue by ghost** [jreklund/php4dvd#35]
Good Day. A great script for personal video collection. Is it possible to have a small field for library number?

For example, I already have my DVDs and BluRays in CSV format with unique identifier to help me find it on the shelf. A field with 6 VARCHAR would be great to reference the ID of the physical unit.

Many thanks.

Gund

**Comment by gundwehsling** [comment]
Thank you. We are using personal notes for the library id for now. Other software I have found in this category is not up to date and was maintained last some years ago.

My preference for a library_id would be alpha number with a dash symbol. It is my preference and that of my friends to use a format such as 'dvd-1234' or 'b00234' to denote medium and id of personal libraries.

I was using Tellico whic is not a web service, it allows adding custom fields.

Perhaps a work around for this migh tbe to include some instruction to customize the template? In this case, the end user can use the 'personal notes' field, but in the template using CSS or similar, the label can be changed?

**Comment by Bloodsoul** [comment]
If this should be a predefined format, I'd like to recommend the following.
rack-shelf-optional_id

The optional id could be an identifier that is labeled on the movie or a section on the shelf.

**Comment by jreklund** [comment]
@gundwehsling And thank you for coming with suggestions; always nice too see the software coming to good use. I had a quick look at Tellico, and implementing a custom fields function looks like a good idea to future proof the software. #37
You can change the label by changing the translation. But it will still say `personal notes` or similar in the database.

@Bloodsoul This field should not be a predefined format; as everyone likely have a library name already set up. But the software can give hints on how a "normal" format can look like.

**Comment by Bloodsoul** [comment]
Thank you for the explanation. That will be perfekt. :)

**Comment by jreklund** [comment]
I'm closing this one as it will be implemented with #37.
