### ISSUE TITLE
cover is not stored at hard disc

### ISSUE THREAD

**Issue by e-skulk** [jreklund/php4dvd#42]
Hi,

The issue happens as follows:
1. I open an already imported movie in edit mode (see my installation)
2. click refresh
3. cover and also IMDB data is successfully fetched (cover is visible at the left)
4. click on store or store and next movie
5. IMDB data is stored successfully in database
6. cover is not stored at hard disc
7. reloading movie details in view mode or search result view does not reveal a cover.

The issue does not happen for new added movies. Here cover is fetched from source and is stored as a jpg-file below movies directory.

My installation of php4dvd is as follow:
- same code base as git master from 2018-10-04.
- php7 + php-gd + php-curl and other dependencies fulfilled
- import process succeeded successfully like described by https://github.com/jreklund/php4dvd/issues/34#issuecomment-381681208
- no errors in error log of apache2 or in development mode

My relevant configuration options:
  $settings["photo"]["movies"] = "./movies/";
  $settings["photo"]["covers"] = $settings["photo"]["movies"]."covers/";
 
  current access rights of movies and covers (access with all rwx rights does also run in this issue)
  /var/www/php4dvd# ls -al movies/
  drwxr-xr-x  3 www-data www-data 4096 Okt  4 08:28 .
  drwxr-xr-x 12 www-data www-data 4096 Okt  3 17:41 ..
  drwxr-xr-x  2 www-data www-data 4096 Okt  3 16:48 covers
  -rw-r--r--  1 www-data www-data   33 Okt  3 16:48 index.php

What may I do to fix it?

**Comment by jreklund** [comment]
I have now released a new version that automatically downloads a image/poster from IMDb in case there aren't one available. I have also made "Download from IMDb" available from the "Title -> Edit -> Update" page. In case you want to download a new poster and fetch new information.
