### ISSUE TITLE
How to reset your category selection?

### ISSUE THREAD

**Issue by GoldMnaPro2014** [jreklund/php4dvd#43]
Hello. Need help in the script. The problem is this: when you select one of the categories and then click on the main page, it does not go to the main page, but remains on the category page. How can I fix this?

**Comment by jreklund** [comment]
Hi, If I guess everything correctly you are doing it like this.
1. Select category: Action
2. Press "php4dvd" or close the browser and come back.
3. You are still on category: Action

If so it's working as intended. It saves where you left off. You need to manually change category again to "All categories" or press:
CTRL+F (focus search field)
END (resets your search)

See: [Keyboard shortcuts](https://github.com/jreklund/php4dvd#keyboard-shortcuts)
