### ISSUE TITLE
New Pages

### ISSUE THREAD

**Issue by GoldMnaPro2014** [jreklund/php4dvd#46]
How to create a new page?

**Comment by jreklund** [comment]
I'm afraid I need more information then that. If you mean a separate page like "About us" it's not possible.
You can only add Movies/TV-shows. And for that press "Add" in the top menu.

**Comment by jreklund** [comment]
@GoldMnaPro2014 Did you get the answer you where looking for? So I close this.

**Comment by warezcmpt** [comment]
Hello i'm also interested by adding a new page.
For example i already added link in the header and redirect go=>contactpage on index.php
But it seems i have some dificulties with smarty...

**Comment by jreklund** [comment]
Hi, adding custom pages are not supported by default, you need to hack in yourself as you already tried. You can look in all includes/* files on how to assign variables and index.php for assigning templates `$Website->assign("main", "users/login.html");`.

Smarty Documentation are always a good start as well, that's how I learn to utilize it.
https://www.smarty.net/docs/en/
