### ISSUE TITLE
Costum pages, news, imdb rating

### ISSUE THREAD

**Issue by Doopsters** [jreklund/php4dvd#47]
I see very future proof in that project. Love to see some new cool future's...
I'm huge movies and tv show's fan, before i had custom made movies collection script, but it needed a lot off work to make it modern version, bootstrap, new software (php, mysql) etc.

So have some ideas:

Add **Custom pages** and a little **news corner**, nothing special, just _title_, _when added_, _content_, _category_, _source link_. 

**IMDB Rating**, Fetching from imdb id. 

I'm already working those requested futures in my personal project. 

One thing where i struggle is how show some info like movie Type, show that output as a little icon. 
Example When adding movie, in field Movie Type and have 3 choose Digital, DVD, Blu-Ray

If i selected ex Blu-ray it show that selections in movie as a Blu-ray icon image. 

Anyway this project looks very cool, love to see more updates and futures :)

**Comment by Scrotchy** [comment]
> I see very future proof in that project. Love to see some new cool future's...
> I'm huge movies and tv show's fan, before i had custom made movies collection script, but it needed a lot off work to make it modern version, bootstrap, new software (php, mysql) etc.
> 
> So have some ideas:
> 
> Add **Custom pages** and a little **news corner**, nothing special, just _title_, _when added_, _content_, _category_, _source link_.
> 
> **IMDB Rating**, Fetching from imdb id.
> 
> I'm already working those requested futures in my personal project.
> 
> One thing where i struggle is how show some info like movie Type, show that output as a little icon.
> Example When adding movie, in field Movie Type and have 3 choose Digital, DVD, Blu-Ray
> 
> If i selected ex Blu-ray it show that selections in movie as a Blu-ray icon image.
> 
> Anyway this project looks very cool, love to see more updates and futures :)

Those are cool futures, i also using this script in my site!

**Comment by countedspore34** [comment]
Adding page or news woult be nice!

How i can add costum fields?

**Comment by jreklund** [comment]
Hi all, thanks for using my version of php4dvd.
1. Custom pages - Personally I just use this to keep track on my ever so growing movie/tv collection. My aim aren't to add this type of functionally, as it will become a fully fletched website.
2. News corner - See above.
3. IMDb Rating - This script already grabs the IMDb rating. Am I missing something?

> I'm already working those requested futures in my personal project.

Great! Grab what you can as it's Open Source. Please leave license intact thought.

> One thing where i struggle is how show some info like movie Type, show that output as a little icon.
Example When adding movie, in field Movie Type and have 3 choose Digital, DVD, Blu-Ray
If i selected ex Blu-ray it show that selections in movie as a Blu-ray icon image.

I'm not quite sure what you mean. Can you make a mock-up?

> How i can add custom fields?

As of right know you can't do it. It's planned for V4. #37
