### ISSUE TITLE
ERROR 500 when adding movie/tv without adding a cover

### ISSUE THREAD

**Issue by jreklund** [jreklund/php4dvd#5]
> Hi! When I trying to add information from IMDB, without adding a cover, I get an error, did someone encounter this? If you add the cover art manually, then everything is fine. https://i.imgbox.com/mZ1K6ov2.gif

Hi @Solmier, please see the FAQ regarding "SSL certificate problem: unable to get local issuer certificate". Your sever can't validate IMDb SSL certificate and a fatal error is encountered. 

In the future, please open an issue instead of commenting on a commit.

**Comment by Solmier** [comment]
Hello jreklund, sorry just registered, did not have time to figure it out, everything works, thank you.

**Comment by jreklund** [comment]
Hi again! Glad everything worked out. Enjoy!
