### ISSUE TITLE
Filter movies by rating exactly pg-0

### ISSUE THREAD

**Issue by Bloodsoul** [jreklund/php4dvd#50]
Currently, the default values for pgMin and pgMax within the search are `0`. If their value is `0`, they are not included in the database query.
Thus, it is currently not possible to filter by a rating of exactly zero.

Since the most rating systems won't have a rating `1`, it can be worked around from users by setting the slider to `0:1`. But one might be confused, that a slider of `0:0` results in displaying all the movies.

**Comment by Bloodsoul** [comment]
Thank you very much.

**Comment by jreklund** [comment]
Your welcome. If you already have downloaded the master and tested it out yourself. Please download it again. I broke "Update all" function, it have now been fixed.
