### ISSUE TITLE
Notes field undefined

### ISSUE THREAD

**Issue by sjmoller** [jreklund/php4dvd#53]
When I try to access $movies[m]->notes in tpl/*/movies/movies/*.html, I get this error message: Undefined property: Movie::$notes.
For some reasone the notes property is not defined in the Movie object. It seems it is imported from the DB, but why is it then undefined in the lists?

**Comment by jreklund** [comment]
I only fetch data that are being used in those templates. In case you want to fetch more information you need to update /includes/movie.search.inc.php

```
// Change what columns to get from the database (movie collection)
$columns = array();
if($templateName === 'poster' || $templateName === 'postertitle')
	$columns = array('`id`','`name`','`year`','`seen`','`own`','`favourite`','`tv`');
if($templateName === 'posterlist' || $templateName === 'listplot')
	$columns = array('`id`','`name`','`year`','`duration`','`rating`','`languages`','`plotoutline`','`seen`','`own`','`favourite`','`tv`','`pg`');
if($templateName === 'list')
	$columns = array('`id`','`name`','`year`','`duration`','`rating`','`languages`','`seen`','`own`','`favourite`','`tv`','`pg`');
```

**Comment by sjmoller** [comment]
Yep. That did the trick. Thx.
Perhaps you should consider adding (nearly) all columns by default.

**Comment by jreklund** [comment]
Great! Glad it worked out for you.

That's the thing, I don't know what other people want to display. So it would be limit to what are currently being used or return all. And it's a slight performance/good practice to only fetch what you really need.

**Comment by sjmoller** [comment]
While it's goot practice not to move alot af data around, it would still be nice to have access to all the data if needed.
Another approach could be the ability to configure wich columns to expose for Smarty. A simple list columns in config/config.php. Then I will not have to modify the code itself, but keep my customizations to where it is supposed to be.
