### ISSUE TITLE
How to change (View Trailer) to (something else) in 'Movie'.     'Top Navigation'  

### ISSUE THREAD

**Issue by charan379** [jreklund/php4dvd#57]
How to change (View Trailer) to (something else) in 'Movie'.     'Top Navigation'  

Im a newbie... Pls help me on this to customise my movie data base I have already tried to change it in default theme but I can't find it.

Thanks in advance.......
@jreklund

**Comment by jreklund** [comment]
Do you mean the translation of the button? If that's the case you find it in the /lang/ folder. If not, you need to be more specific.

**Comment by charan379** [comment]
No let say I want to change [ View Trailer ] to [ Parvai YT ]

Is it possible
