### ISSUE TITLE
a way to get the information about "seen"

### ISSUE THREAD

**Issue by dergurke** [jreklund/php4dvd#6]
hey, sorry english isnt my first language.

i have a little question. i want to put the eye (seen) on the mainpage but dont know how to get the information about this. i tried it with $movies[m]->seen but this dint helped me, every movie is unseen. sorry, im not skilled in php.

an example what im looking for:

<img src="https://endriel.mekaku.de/firefox_2017-07-23_09-10-57.png">

**Comment by jreklund** [comment]
You will need to modify two files to be able to change the chosen layout.

`includes\movie.search.inc.php` row 63
```
$columns = array('`id`','`name`','`year`','`duration`','`rating`','`languages`','`plotoutline`','`seen`');
```
`tpl\default\movies\listplot.html` row 5

```
<div class="list-movie-title">
	{$movies[m]->name|htmlentities:3:'UTF-8'} <small>({$movies[m]->year|htmlentities:3:'UTF-8'})</small>
	{if $movies[m]->seen}
		<i class="fa fa-eye fa-fw" title="{$smarty.const.SEEN|htmlentities:3:'UTF-8'}" aria-hidden="true"></i>
	{else}
		<i class="fa fa-eye-slash fa-fw" title="{$smarty.const.UNSEEN|htmlentities:3:'UTF-8'}" aria-hidden="true"></i>
	{/if}
</div>
```

You will also need to change `postlist.html` and `list.html` if you want "seen" on those layouts too. On `list.html` you also need to add the seen value from the database, that is located at row 65 of `movies.saerch.inc.php`.

**Comment by dergurke** [comment]
thank you very much, works fine for me
