### ISSUE TITLE
Could not connect to database when i install this project 

### ISSUE THREAD

**Issue by roobinhoood** [jreklund/php4dvd#60]
Hi all, 
Please help me, i am faced a issue when i install this projects.
The error is : could not connect to database "php4dvd
Foe better reference m shar screenshot,
Thanks
Robin
![IMG_20200420_001824](https://user-images.githubusercontent.com/63975517/79697057-24ad4400-829e-11ea-8916-1da5b9e149c8.jpg)

**Comment by jreklund** [comment]
Hi, you need to manually create the database. That part aren't done automatically.

**Comment by roobinhoood** [comment]
Could you please share a video how to do this, or share step by step format, because i am beginner, 
Please help me?.
Thanks
Robin

**Comment by armdan** [comment]
Google " how to set up MySQL and you might want to search also PHPMyAdmin". 
After you set up MySQL or MariaDB server then you can create a database for php4dvd.

**Comment by jreklund** [comment]
As the url says http://localhost. You most likely already have phpMyAdmin installed, if you are using XAMPP or WampServer (Windows).

It should be under; http://localhost/phpmyadmin
1. Login using your username / password
2. Select **Databases** in the top menu
3. Type **php4dvd** in the _Database name_ field and select **utf8mb4_unicode_520_ci** or utf8mb4_unicode_ci
4. Press **create**

Now you can install php4dvd with the web based wizard.

**Comment by roobinhoood** [comment]
I have successfully implemented and login successfully with admin and guest user.

Problem: If open another tab and hit site it again opens with direct home page, without asked to login form, now cane we fixe this login session, i want it always open with login form. 
Please help,
Thanks
Robin

**Comment by Bloodsoul** [comment]
I don't really get what your problem is.

Once you are logged in, you are logged in until your session runs out or you log out manually. This session is also valid in another tab within the same browser or even in a new window of the same browser.

If another person instead is browsing the page, they get the login form, since they don't have your session. You can test this by using another browser or the incognito mode.

**Comment by roobinhoood** [comment]
If another person hit the my php4dvd site from different web browser or different devices they did not get log in page form, they get dirct show tha home page. 
My atteched screen shots for better refrence.
![Screenshot_20200421-201018](https://user-images.githubusercontent.com/63975517/79879413-42002080-840c-11ea-805c-f5c3f594533d.png)

**Comment by Bloodsoul** [comment]
They are not logged in. If I visit your site, I cannot manage anything.
If you just want that your users have to login to even view the movie lists, you can just set the option `$settings["user"]["guestView"]` to `false` in your `config/config.php` file.

**Comment by roobinhoood** [comment]
Now its working fine, thanks.
Can we add wacth now button to view videos file form my locally drive "d:/all_hollywood_bluray_movie"

**Comment by jreklund** [comment]
I commented on the other issue/thread regarding this. There are a vlc-player branch, but it's not recommended for security issues. And it will only work locally, not streaming over the internet.

I'm closing this one as the issue at hand are solved. Please see the FAQ in the readme and check `config/config.default.php` as it's most likely a setting you want to change.
