### ISSUE TITLE
Some more features in nevigation bar

### ISSUE THREAD

**Issue by roobinhoood** [jreklund/php4dvd#62]
I just want to add more features in navigation bar. i have already add some navigation list option like( dual audio movie, hollywod movie, bollywood movie). Now help me to written the code scripts related to this added features.
Thanks
Atul
![1588164925252870272138132761548](https://user-images.githubusercontent.com/63975517/80598379-e1459900-8a46-11ea-8c8b-f042e630b9d5.jpg)

**Comment by jreklund** [comment]
Hi, I'm not taking feature requests at the moment. It looks like you want to add more options of sorting/categories them. You can add any text you want under a movie/tv-shows "Genres" and it will pop up "Categories", so you can sort them that way.

**Comment by roobinhoood** [comment]
I have add all movies under movie genres, now i want categories movie by dual audio and hollywod, etc. This function is not in this template, so please tell me how to write the code for either.
Thanks
Robin

**Comment by roobinhoood** [comment]
Hi guys.
Can any help me?

**Comment by jreklund** [comment]
No one here can teach you how to code PHP, SQL, HTML etc. You need learn that yourself. All the code are technically there, it needs to be duplicated. Just put those "tags" in the Genres and you can filter them in Categories.
