### ISSUE TITLE
Favorites for an individual user

### ISSUE THREAD

**Issue by GoldMnaPro2014** [jreklund/php4dvd#66]
Hi, I need help, I wanted to create a page with selected films so that an individual user can add films to his collection (I registered it), but I can't implement the code "Add to collection" and "Remove from collection", can you help me with this question?

**Comment by jreklund** [comment]
I'm afraid this is out of scope of what the project are intended for. It's single owner/user mode and would require new database tables etc to get it to work.

Locking it as no one else shown interest in it. Hopefully you have sorted it out or you would be required to hire someone for the job.
