### ISSUE TITLE
How do I get a selection to stream?

### ISSUE THREAD

**Issue by wagb283** [jreklund/php4dvd#71]
I didn't want to hack in to the php before asking if there's already an accommodation to stream a file.
I've got this up and running (thanks, btw) on a local lan so others in the family can use it to stream files. The front end works fine, now I need to know where to plug-in (php file, line?) to use the selection a user makes to get to a file, without messing up all the work you've already put into it. 

Great work by the way, much nicer interface than the python server I'm currently running, love the imdb feature.

**Comment by jreklund** [comment]
You can test out the beta branch #11, it will let you open trailers from your local network instead.

Don't think I will implement a native player for this, it's for hard copies and not digital ones.
