### ISSUE TITLE
Search not working properly on mobile 

### ISSUE THREAD

**Issue by comadde** [jreklund/php4dvd#72]
If you wisit this site on a mobile and use the search function, then you want to change the a different search option you can't erase the old text.

Can this be fixed?

**Comment by jreklund** [comment]
What device are you currently using? Works find for me (Samsung S10e using Chrome).

**Comment by comadde** [comment]
Samsung S10+ with chrome. 

But now I tested it work. So I can be something in chrome... 🤔
