### ISSUE TITLE
[FEATURE] Add TMDB as default for poster

### ISSUE THREAD

**Issue by warrengalyen** [jreklund/php4dvd#75]
When adding new movies, the current configuration defaults to IMDB which almost always uses the theatrical poster. These poster images are not ideal as they are plastered with  release date and cast information. It would be nice to have a configuration option to automatically add poster images from TMDB. It's a bit of a hassle to manually download and replace the default image every time I add a movie.

**Comment by jreklund** [comment]
Don't know if #67 includes it, you can try it out. Don't have the time to develop it myself as I wan't to move away from bundling more code and start using Composer instead.

**Comment by jreklund** [comment]
Hi, will be closing this one as it's not something that will happen for V3 and no idea what will be used for V4, if that's something I will be building.
