### ISSUE TITLE
Poster image does not download/update from IMDB if one already exists...

### ISSUE THREAD

**Issue by dewalters21** [jreklund/php4dvd#77]
If you edit a movie or show and select the checkbox to download the poster from IMDB, it does not actually download the IMDB poster if one already exists for the movie.  I'm thinking that if I check that box and click save it should download the current poster from IMDB and overwrite the existing poster in the system.

**Comment by jreklund** [comment]
That's what the box does, but your browser caches the image so you need to flush your cache.
CTRL+F5 in Windows.

**Comment by dewalters21** [comment]
My apologies.  Thank you for responding!

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jreklund** [comment]
No worries. Your welcome!
