### ISSUE TITLE
$movies[m]

### ISSUE THREAD

**Issue by alain93** [jreklund/php4dvd#78]
Hello,
I'm trying to add the movie format in postertitle.html, alas format does not seem to be available.
I can return name, year with $movies[m]->name or $movies[m]->year, but not format.
Why is that?
and how could I show format?

**Comment by jreklund** [comment]
Hello,

I have limited the number of columns returned from the database to get a performance boost.
You need to modify `includes/movie.search.inc.php` and add `format`.

From:
```
// Change what columns to get from the database (movie collection)
$columns = array();
if($templateName === 'poster' || $templateName === 'postertitle')
	$columns = array('`id`','`name`','`year`','`seen`','`own`','`favourite`','`tv`');
```

Into:
```
// Change what columns to get from the database (movie collection)
$columns = array();
if($templateName === 'poster' || $templateName === 'postertitle')
	$columns = array('`id`','`name`','`year`','`seen`','`own`','`favourite`','`tv`','`format`');
```

**Comment by alain93** [comment]
oh wow! thanks, this thing was driving me nuts :)
