### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by nickcharles23** [jreklund/php4dvd#86]
Hi,
Just installed php4dvd latest version and cannot get it to work. I cannot find why because no information can be found anywhere on why php4dvd is not working. I'm using Desktop: Cinnamon 5.6.8 tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy and MYSQL 8.1 with PHP 8.2.7 .

The problem: After logging in The first page is blank with a swirling circle.
![php4dvd1](https://github.com/jreklund/php4dvd/assets/137850102/b8952d79-b4c6-4f34-829f-539c07dedbb5)

Then I try to add a movie and do get results.
![php4dvd2](https://github.com/jreklund/php4dvd/assets/137850102/07678fb0-d1bf-4fbb-868e-cff18a40d92d)

When I try to save the movie I get localhost is currently unable to handle this request.
![php4dvd3](https://github.com/jreklund/php4dvd/assets/137850102/69162a7e-bb17-4b1e-930c-332da4df28c4)

I believe I have all the requirements required to run the program. I even may sure the mysql PDO driver is working. Have I missed something during the installation? One install requirement was not clear to me which is, Create a database for php4dvd on your web server, as well as a MySQL (or MariaDB) user who has all privileges for accessing and modifying it. I'm using root as the user. Do I need to use a different username?

Can anyone help with troubleshooting suggestions/steps so I can get php4dvd working. With these suggestion then one can add them as a a help file for troubleshooting tips as part of the distribution.

Thanks

**Comment by jreklund** [comment]
php4dvd don't support PHP 8.2 at this time, so could be simple as that. Try PHP 8.0 or 8.1.
