### ISSUE TITLE
MYSQL Fields not Created Correctly During Install

### ISSUE THREAD

**Issue by nickcharles23** [jreklund/php4dvd#87]
During my troubleshooting on why php4dvd would not save data from imdb I found the following:
The database fields are missing when php4dvd does an installed when creating the database. For example votes, pg, and mdbid are ones that where not created.  The error received looks like "An error occurred: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mpaa' in 'field list'" would be another field missing that was not created. Thus currently php4dvd is not usable with a fresh install of the latest version  available.

I would also assume that previous installs do not contain theses fields and one would not be able to add a new movie to the database from imdb when one does an upgrade. I would suggest not to upgrade if the version one is using is working and can still add movies.

**Comment by jreklund** [comment]
Sorry about your troubles and for all other folks trying to use a fresh install since 3.11.1 and onwards. Upgrades works fine, I just forgot to include 3.4, 3.5, 3.6 and 3.7 updates in the installation file. 3.8 where included. 

This is a follow up thread of #86.
