### ISSUE TITLE
application for my communauty ?

### ISSUE THREAD

**Issue by sachaz** [jreklund/php4dvd#90]
Hi,

first of all thanks a lot for this software ! It's really simple and efficient as I wish !

1. I using it to share movies I ha seen with my community and I wish some new fields for that: new role : viewer which could add a note for my instance and left a comment with his nickname. And the admin could be alerted on comments.

1. Another missing field could be customs ones, for exemple: I'm using the personal notes to set the local path of the file.

**Comment by jreklund** [comment]
Thanks, glad you liked it! 

1) That's not a personal goal of mine, so not something I will be developing or supporting, you need to fork the project and developing your own version.

2) That's a feature that have been suggested before and something I'm considering for version 4.0. There are no ETA at all, as version 3 works great for me, if you don't count all the legacy code...

**Comment by sachaz** [comment]
Thanks for your answer !
