### ISSUE TITLE
Movie Search Failure

### ISSUE THREAD

**Issue by nickcharles23** [jreklund/php4dvd#92]
Hi, for some reason the add title function stop working using the following http://localhost/php4dvd/?go=add&imdbid=tt0272045 in the browser adress bar. If seems to just happen recently. Can anyone help me to find out why? 
Using PHP 8.1.26
Configuration File (php.ini) Path	/etc/php/8.1/apache2
Loaded Configuration File	/etc/php/8.1/apache2/php.ini
Scan this dir for additional .ini files	/etc/php/8.1/apache2/conf.d
Linux Stutong 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 2 18:01:13 UTC 2 x86_64
Apache/2.4.52 (Ubuntu) Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

Using the standard search using title seems to be working for movies. But need this function for TV programs. Any assistance in troubleshooting would be appreciated.

Thanks

**Comment by jreklund** [comment]
I'm afraid you aren't providing enough information on what is happening when it stopped working. That ID works fine on my system. Check your error logs for PHP in case it's crashing.

As you never came back and answered my following up questions in your latest issue #88 , I had no idea why your "TV series" didn't pop up in the search bar. That one are a TV-special, and are hidden by default.

If you set [$wantedTypes](https://github.com/jreklund/php4dvd/blob/master/includes/movie.update.inc.php#L34C1-L40) to `null`, it will look for all types. Or you add the ones you think is missing from [TitleSearch](https://github.com/tboothman/imdbphp/blob/master/src/Imdb/TitleSearch.php#L7-L16).

There should be no `tt` in the url thought.
`http://localhost/php4dvd/?go=add&imdbid=0272045`

**Comment by nickcharles23** [comment]
It was the tt in the url. My error. It was awhile since I added any TV programs.
As to #88, item 2 is still an issue for me can't add a movie manual.  The  tip Add the movie/tv-show manually with only imdb, title and year. fails. I believe the database is looking for additional required fields.

With the url hack I'm ok since I have my complete collection loaded up.
Thanks for the tips  as well.
