### ISSUE TITLE
Unable to add a new movie info or edit an existing one

### ISSUE THREAD

**Issue by 8tm** [jreklund/php4dvd#93]
Hi,

after long time I finally updated my server and I had to update php4dvd and... everything looks fine, but I can't create/add new movie or edit/save existing one.

It would be nice to add logs feature to php4dvd, but for now I would like to know how can I help to fix this issue.

I have installed:
php8.2	        8.2.7-1
php8.2-bcmath	8.2.7-1
php8.2-cli	8.2.7-1
php8.2-common	8.2.7-1
php8.2-curl	8.2.7-1
php8.2-fpm	8.2.7-1
php8.2-gd	8.2.7-1
php8.2-imagick	3.7.0-4
php8.2-intl	8.2.7-1
php8.2-mbstring	8.2.7-1
php8.2-mysql	8.2.7-1
php8.2-opcache	8.2.7-1
php8.2-readline	8.2.7-1
php8.2-soap	8.2.7-1
php8.2-xml	8.2.7-1
mysql-common    5.8+1.1.0

I just found that php4dvd doesn't support PHP 8.2 and maybe because of that I have this issue (not sure).
Have you ever seen that bug?

I hope you will update PHP support soon :)

**Comment by jreklund** [comment]
php4dvd will write to your servers PHP error logs, so check those for errors. There where some problems with bundled libraries with PHP 8.2, but haven't checked those in a while, if those problems have been resolved.

**Comment by tmakinen** [comment]
Not sure about PHP 8.2 but i have been running php4dvd inside podman container with PHP 8.3 just fine.
