### ISSUE TITLE
add a Hyperlink to Trailer URL 

### ISSUE THREAD

**Issue by dwk000** [jreklund/php4dvd#94]
How to add

http://localhost/php4dvd/movies/trailers/ArmageddonTrailer.mp4

to Trailer URL 

or where can I change php script to allow above link

**Comment by jreklund** [comment]
Hi, you have two options, but I don't know if it will open the browsers embedded video-player.
1. Add a domain to your server e.g. movie-collection.local
2. Remove `url` class from this line [update.html#L275](https://github.com/jreklund/php4dvd/blob/master/tpl/default/movies/update.html#L275)
