### ISSUE TITLE
Change default format option

### ISSUE THREAD

**Issue by userhs6719** [jreklund/php4dvd#96]
I've looked everywhere for a way to change the default "format" option when adding a new title. Currently, it's filled in with "Blu-ray" and I'd like to be able to edit this. (I don't even have any blu-rays in my collection)

**Comment by jreklund** [comment]
Hi, it's a hard coded value in the templates file.

`{$smarty.const.BLU_RAY|escape}`
https://github.com/jreklund/php4dvd/blob/95f65297a518d737371f6a37720513ec311f99f0/tpl/default/movies/update.html#L156

That constant is from the language files.
https://github.com/jreklund/php4dvd/blob/95f65297a518d737371f6a37720513ec311f99f0/lang/en.inc.php#L131

**Comment by jreklund** [comment]
Won't be adding a new features for this one. Should be implemented together with #8 and #97.
