### ISSUE TITLE
Additional information in list view

### ISSUE THREAD

**Issue by markoku** [jreklund/php4dvd#99]
Hi!

First, I want to thank for this awesome package.

I have been using php4dvd for long time. I was forced to install and upgrade to version 3 because my old rig broke down and that was that. I use this "wrong" and don't use imdb or any other external source, just as a list of movies (with own information).

What I want is in list view there would be movie name, year, aka, personal notes, loaned to -cells. In old version I was able to do that, but with this new layout I am lost.

I tried this (movies/movies/list.html):
                                <div class="movie-title">{$movies[m]->aka|escape} </div>
                                <div class="movie-notes">{$movies[m]->notes|htmlentities:3:'UTF-8'} </div>

Doesn't print out anything. What am I doing wrong here?

**Comment by jreklund** [comment]
Hi! Have you cleared the templates from /compiled-folder? It converts Smarty templates into PHP-code and you most likely are running the compiled versions before your changes.

**Comment by markoku** [comment]
I have not cleared that (didn't know I have to). I'll clear that and test it, maybe tomorrow. Thanks for tip!

**Comment by markoku** [comment]
Didn't help. For some reason info isn't pulled up from database. I am clearly missing something..

When movie is opened all info is there, but can't pull them in front page.

**Comment by jreklund** [comment]
I forgot about that part. I only fetch the fields that I need.
You can change it here; [movie.search.inc.php#L133-L138](https://github.com/jreklund/php4dvd/blob/master/includes/movie.search.inc.php#L133-L138)

**Comment by markoku** [comment]
Ah, that explains a lot. Lets edit that next. Thank you.

**Comment by markoku** [comment]
This did the job! I am grateful.

**Comment by jreklund** [comment]
Great that you managed to modify the script to your use case! :)
